name: CI 
on: [push, pull_request]

jobs:
  test:
    name: Testing 
    runs-on: ubuntu-latest
      strategy:
        matrix:
          go-version: [1.14.x]
      steps:
        - uses: actions/checkout@v2
        - name: Set up Go ${{ matrix.go-version }}
          uses: actions/setup-go@v2
          with:
            go-version: ${{ matrix.go-version }}
         - name: Run Tests
           run: go test -v -cover -covermode=count -coverprofile=coverage.out ./...
         - name: Convert Coverage 
           uses: jandelgado/gcov2lcov-action@v1.0.9
         - name: cover all 
           uses: coverallsapp/github-action@v2.2.3
           with: 
             github-token: ${{ secrets.GITHUB_TOKEN }}
             path-to-lcov: coverage.lcov  

      lint:
        runes-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: get source 
          
          - name: Setup 
            uses: actions/setup-go@v4
            with:
              go-version: 1.21.x
          - name: Run lint
            uses: golangci/golangci-lint-action@v3
            with:
              version: latest
              args: golangci-lint run ./...


